### ISSUE TITLE
musl-libc missing for armv7m

### ISSUE THREAD

**Issue by greglink** [bootlin/toolchains-builder#19]
Unclear why (it may simply be a documentation issue), but only uclibc is supported in the drop-down for armv7m architectures currently. I'm specifically interested in musl-libc on such a platform, so if it is possible, I'd love to see it, and if not, I'd also be interested in what the blocking problem is.

**Comment by RomainNaour** [comment]
Hello,

armv7m stand for ARM Cortex-m4.
Since only uClibc-ng support noMMU configuration, this is why toolchain-builder doesn't provide such toolchain (musl toolchain needs an MMU).

Best regards,
Romain

**Comment by richfelker** [comment]
musl can support nommu targets with standard ELF binaries as long as they're PIE, but FDPIC is on the agenda. Main obstacle to me getting it done is toolchain side stuff. I need versions of the toolchain FDPIC support patches that apply in musl-cross-make, since it's still not upstream in a released and supported gcc version yet.

**Comment by tpetazzoni** [comment]
As explained by @richfelker, the support for ARM noMMU with musl is not ready, which is why it cannot be enabled in toolchain-builder. We'll be happy to add support for that once supported by musl/binutils/gcc.
