### ISSUE TITLE
armv7-eabi architecture

### ISSUE THREAD

**Issue by T-Troll** [bootlin/toolchains-builder#20]
Can you please made a toolchain for armv7 softfp with clib 2.24?
I have this kind of board, now use armv5 toolchain.

T.I.A.

**Comment by tpetazzoni** [comment]
I'm not sure what you mean by "clibc". I suppose you are talking about glibc, because it's the only C library that I know of that ever released a 2.24 version. However, glibc 2.24 is very old, we're not going to produce a toolchain with such an old glibc version. Why do you need such an old glibc version ? Also, is there a motivation to use softfp on an ARMv7 core that can support hardfp ?

**Comment by T-Troll** [comment]
You are right in both (and excuse me for typo, please - glibc, of course).
But this is Cineese-made board (more precisely, from HiSilicon). Yes, it supports hardfp, but this bastards compile their essential libraries using softfp. And no source codes, as well.
So it's only way to handle it.

**Comment by tpetazzoni** [comment]
You can use a more recent glibc version and re-use their binary blobs: glibc provides an ABI backward compatibility guarantee. But of course indeed you need a softfp toolchain.

**Comment by T-Troll** [comment]
... And have glibc hell in os. It's even harder to avoid it.
I try to use common gcc/g++-arm-linux-gnueabi, but libatom and kernel glibc opens me hell on earth.

And i even can't use their tollchain - it's 32-bit only. I use wsl - so no way.

**Comment by tpetazzoni** [comment]
I'm closing this issue, because we're not going to produce toolchains based on glibc 2.24.
