### ISSUE TITLE
'not found' Issue when trying to use toolchain

### ISSUE THREAD

**Issue by dangerousHobo** [bootlin/toolchains-builder#34]
I've downloaded the toolchain and when I try to use it I get the following:

```
/build # ./armv7-eabihf--musl--bleeding-edge-2020.02-2/bin/arm-linux-cc -v
/bin/sh: ./armv7-eabihf--musl--bleeding-edge-2020.02-2/bin/arm-linux-cc: not found
```

But the file is there:

```
/build # ls -l ./armv7-eabihf--musl--bleeding-edge-2020.02-2/bin/arm-linux-cc
lrwxrwxrwx    1 root     root            17 Apr  4 17:31 ./armv7-eabihf--musl--bleeding-edge-2020.02-2/bin/arm-linux-cc -> toolchain-wrapper
```

My host is x86_64:

```
/build # uname -m
x86_64
/build # cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.5
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

Any ideas on what is wrong?

**Comment by RomainNaour** [comment]
Hi,

The bootlin toolchain must be used on a Linux distribution based on glibc.
If you are using alpine linux, then the dynamic loader doesn't find the libc (glibc) because Alpine use musl libc.
Toolchain-builder use Debian jessie to build the toolchain:
https://github.com/bootlin/toolchains-builder/commit/dee4969ca5852158a89160266ae9c25756e3995a

Best regards,
Romain
