### ISSUE TITLE
Toolchain platform name

### ISSUE THREAD

**Issue by sergey-suloev** [bootlin/toolchains-builder#50]
When I build aarch64 toolchain the script produces "aarch64-buildroot-linux-gnu" platform name. Is this possible to fix it for the classical "aarch64-linux-gnu" ? So that tools look like "aarch64-linux-gnu-gcc" etc

**Comment by tpetazzoni** [comment]
If you're building the toolchain yourself, you can adjust the vendor part of the tuple by changing BR2_TOOLCHAIN_BUILDROOT_VENDOR option. Otherwise, our pre-built toolchains have binaries prefixed with <arch>-buildroot-<os>-<abi>, but also have a symlink <arch>-<os>-<abi> so they do look like arch64-linux-gnu-gcc like you asked.
